---
name: Publish packages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
      image: public.ecr.aws/jsii/superchain:1-bookworm-slim-node20

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          make install
          sudo apt-get update
          sudo apt-get install -y tree

      - name: Build source w/ jsii
        run: |
          lambda/build
          npx jsii
          make validate-package

      - name: Build packages w/ jsii-pacmak
        run: |
          npx jsii-pacmak --verbose
          tree dist

      - name: Publish to npm
        run: npx publib-npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to PyPI
        run: |
          export PIP_BREAK_SYSTEM_PACKAGES=1
          npx publib-pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: Publish to NuGet
        run: npx publib-nuget
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_TOKEN }}
#
#      - name: Publish to Maven GitHub
#        run: npx publib-maven
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GITHUB_REPOSITORY: ${{ github.repository }}
