---
name: Test

permissions:
  contents: read

concurrency:
  group: test
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDC token for assuming the AWS role
      contents: read # checkout

    defaults:
      run:
        shell: bash

    container:
      image: public.ecr.aws/jsii/superchain:1-bookworm-slim-node20

    steps:
      - uses: actions/setup-node@v7
        with:
          node-version: 24.x

      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v6
        env:
          cache-name: cache-node-modules
        with:
          path: .npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          set -euo pipefail
          make install
          (cd test && make install)
          sudo apt-get update
          sudo apt-get install -y tree

      - name: Linting
        run: make eslint

      - name: Set Build Permissions
        run: |
          set -euo pipefail
          mkdir $GITHUB_WORKSPACE/test/cdk.out
          chmod 777 $GITHUB_WORKSPACE/test/cdk.out --recursive
          chmod 777 $GITHUB_WORKSPACE/lambda --recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy & Destroy
        run: |
          set -euo pipefail

          function get_secret_values() {
            AWS_REGION=us-east-1 aws secretsmanager describe-secret \
              --secret-id ec2-ssh-key/CFN-signing-key/private \
              --query 'Tags[?Key==`Test`].Value' --output text
          }

          cd test
          make deploy get-secret-values
          if [ "$(get_secret_values)" != "default" ]; then
            echo "Unexpected secret value"
            exit 1
          fi

          TAG_VALUE=working make deploy
          if [ "$(get_secret_values)" != "working" ]; then
            echo "Unexpected secret value"
            exit 1
          fi

          make DESTROY

      - name: Build source w/ jsii
        run: |
          lambda/build
          npx jsii
          make validate-package

      - name: Build packages w/ jsii-pacmak
        run: |
          set -euo pipefail
          npx jsii-pacmak --verbose
          tree dist
